### ISSUE TITLE
No code ?

### ISSUE THREAD

**Issue by nityansuman** [Leci37/stocks-prediction-Machine-learning-RealTime-telegram#10]
Is the code available in some different branch? I don't see any!

**Comment by makovez** [comment]
Hi, not for now.

We decided to remove to hide the code for now, but if you are interested in the project or wish to collab please text me on telegram @sbongown and we can discuss about it.

**Comment by makovez** [comment]
Hi, not for now.

We decided to remove to hide the code for now, but if you are interested in the project or wish to collab please text me on telegram @sbongown and we can discuss about it.

**Comment by skhonsha** [comment]
I can`t find this telegram id

**Comment by makovez** [comment]
t.me/sbongown

**Comment by Leci37** [comment]
Good morning ,

You can find the code here:
I have just updated the documentation and the erroneous paths , you can see it at
https://github.com/Leci37/stocks-prediction-Machine-learning-RealTime-telegram/tree/master#quick-start-up-run-your-own-models
I'm closing the ticket.

P.S.: I always welcome a second opinion on https://github.com/Leci37/stocks-prediction-Machine-learning-RealTime-telegram/tree/master#possible-improvements
