### ISSUE TITLE
Some files for quick-start not Found

### ISSUE THREAD

**Issue by charleshm** [Leci37/stocks-prediction-Machine-learning-RealTime-telegram#11]
Thans for your good job!

Utils/API_alphavantage_get_old_history.py
yhoo_generate_big_all_csv.py

not found these files, change name?

**Comment by Leci37** [comment]
Good morning , 

I have just updated the documentation and the erroneous paths , you can see it at
https://github.com/Leci37/stocks-prediction-Machine-learning-RealTime-telegram/tree/master#quick-start-up-run-your-own-models
I'm closing the ticket.


P.S.: I always welcome a second opinion on https://github.com/Leci37/stocks-prediction-Machine-learning-RealTime-telegram/tree/master#possible-improvements

**Comment by Leci37** [comment]
If you find a solution please report it to me publicly or privately (leciluis@gmail.com).
