### ISSUE TITLE
Can we use any other API as source instead of yahoo?

### ISSUE THREAD

**Issue by jeni1616** [Leci37/stocks-prediction-Machine-learning-RealTime-telegram#12]
I don't think yahoo provides all information needed for historic data. I am from India so even fewer options here. Any way to use KITE API? 
https://kite.trade/docs/connect/v3/changelog/#historical-data
Some getting started help on this code modification will help :)
Thanks.

**Comment by Leci37** [comment]
You can start from here your modifications 
https://github.com/Leci37/stocks-prediction-Machine-learning-RealTime-telegram/blob/bbb1fa8d3ea3ad9924c5c43324c1d92654f56c5f/yhoo_history_stock.py#L82 

Thank you read the project
